name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dslx_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Install libc++ from llvm-18
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          cd /tmp/
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get install -y libc++-18-dev libc++abi-18-dev

      - name: Install protobuf compiler
        run: |
          wget https://github.com/protocolbuffers/protobuf/releases/download/v29.1/protoc-29.1-linux-x86_64.zip
          unzip protoc-29.1-linux-x86_64.zip -d protoc
          sudo mv protoc/bin/protoc /usr/local/bin/protoc
          sudo mv protoc /tmp/  # Move these out of the way to not interfere with build.
          sudo mv protoc-*.zip /tmp/  # Move these out of the way to not interfere with build.
          # Emit the protobuf compiler version number.
          protoc --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse xlsynth-versions.toml
        id: versions
        run: |
          CRATE_VERSION=$(grep '^crate' xlsynth-versions.toml | sed 's/.*"\([0-9.]*\)".*/\1/')
          DSO_VERSION=$(grep '^dso' xlsynth-versions.toml | sed 's/.*"\([0-9.]*\)".*/\1/')
          echo "CRATE_VERSION=$CRATE_VERSION" >> $GITHUB_ENV
          echo "DSO_VERSION=v$DSO_VERSION" >> $GITHUB_ENV

      - name: Download and rename libxls
        run: |
          XLSYNTH_VERSION=${{ env.DSO_VERSION }}
          BASE_URL="https://github.com/xlsynth/xlsynth/releases/download/${XLSYNTH_VERSION}"
          LIB_FILE="libxls-ubuntu2004.so"
          echo "Downloading ${BASE_URL}/${LIB_FILE}"
          curl -fILs "${BASE_URL}/${LIB_FILE}" | head -n 1  # sanity check (expects HTTP/2 200)
          curl -L -o "${LIB_FILE}" "${BASE_URL}/${LIB_FILE}"
          curl -L -o "${LIB_FILE}.sha256" "${BASE_URL}/${LIB_FILE}.sha256"
          EXPECTED=$(cut -d' ' -f1 "${LIB_FILE}.sha256")
          echo "${EXPECTED}  ${LIB_FILE}" | sha256sum -c -
          mv "${LIB_FILE}" "libxls-${XLSYNTH_VERSION}-ubuntu2004.so"
          ls libxls-*.so
          file libxls-*.so
          export LD_LIBRARY_PATH=$(pwd):$LD_LIBRARY_PATH
          sudo ln -s ${PWD}/"libxls-${XLSYNTH_VERSION}-ubuntu2004.so" /usr/lib/

      - name: Download xlsynth binaries
        run: |
          python download_release.py -o dependencies/ -p ubuntu2004 -v ${{ env.DSO_VERSION }}

      - name: Install Rust nightly toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly

      - name: Install xlsynth-driver using Cargo
        run: |
          cargo +nightly install -vv xlsynth-driver --version ${{ env.CRATE_VERSION }}

      - name: Note xlsynth-driver version
        run: |
          ldd $(which xlsynth-driver)
          LD_DEBUG=libs xlsynth-driver version
          #xlsynth-driver version

      - name: Set up Bazelisk
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          sudo curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.23.0/bazelisk-linux-amd64 -o /usr/local/bin/bazel
          sudo chmod +x /usr/local/bin/bazel
          bazel version

      - name: Download and unpack DSLX standard library
        run: |
          XLSYNTH_VERSION=${{ env.DSO_VERSION }}
          BASE_URL="https://github.com/xlsynth/xlsynth/releases/download/${XLSYNTH_VERSION}"
          STD_LIB_FILE="dslx_stdlib.tar.gz"
          echo "Downloading ${BASE_URL}/${STD_LIB_FILE}"
          curl -fILs "${BASE_URL}/${STD_LIB_FILE}" | head -n 1
          curl -L -o "${STD_LIB_FILE}" "${BASE_URL}/${STD_LIB_FILE}"
          curl -L -o "${STD_LIB_FILE}.sha256" "${BASE_URL}/${STD_LIB_FILE}.sha256"
          EXPECTED=$(cut -d' ' -f1 "${STD_LIB_FILE}.sha256")
          echo "${EXPECTED}  ${STD_LIB_FILE}" | sha256sum -c -
          tar -xzf "${STD_LIB_FILE}" -C dependencies/

      - name: Run presubmit script
        run: |
          python3 run_presubmit.py \
            --xlsynth-tools $(pwd)/dependencies \
            --xlsynth-driver-dir $(dirname "$(which xlsynth-driver)") \
            --dslx-path dependencies/dslx_stdlib
